import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {  ThemeProvider } from "@/context/ThemeContext";
import ThemeParent from "@/components/themeParent";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <ThemeParent>{children}</ThemeParent>
        </body>
      </ThemeProvider>
    </html>
  );
}
